class_name WorldConfig
extends RefCounted
## Plain per-game configuration object [plan T0.5]: seed + every tuning,
## world, and founding option from the setup-and-menus spec (§3–§5), plus the
## quicken budget — a GAMEPLAY constant, deliberately not a graphics setting
## [setup §7.1, algo §14]. Chosen at New Game, baked into the save, locked
## once a run begins. Presentation never writes to this after start.

const GENERATION_PACES := ["languid", "balanced", "brisk"]
const MORTALITIES := ["gentle", "normal", "harsh", "brutal"]
const DISCOVERY_PACES := ["slow", "normal", "fast"]
const DIVINITIES := ["humble", "normal", "ascendant"]
const CHAOS_LEVELS := ["calm", "normal", "capricious"]
const CIVILIZATION_SCALES := ["intimate", "kingdom", "civilization"]
const FAITH_MODES := ["coexist", "mild_drift", "secularizing"]
const REGION_SIZES := {"small": 3, "medium": 6, "large": 12}
const RESOURCE_ABUNDANCES := ["sparse", "normal", "lush"]
const HAZARD_FREQUENCIES := ["calm", "normal", "volatile"]
const BIOME_VARIETIES := ["uniform", "varied"]
const TEMPERAMENTS := ["hardy", "curious", "social", "devout", "ambitious"]
const BAND_SIZE_MIN := 3
const BAND_SIZE_MAX := 8
const MAX_LEANINGS := 2
const DEFAULT_LEANINGS := ["curious"]
const DEFAULT_QUICKEN_BUDGET := 300

# Tuning sheet [setup §3] — defaults are the spec's bold levels.
var generation_pace := "balanced"
var mortality := "normal"
var discovery_pace := "normal"
var divinity := "normal"
var chaos := "normal"
var civilization_scale := "kingdom"
var faith_enlightenment := "mild_drift"

# World [setup §4]
# 0 is a placeholder: the New Game wizard supplies a random or typed seed
# (via Rng-side rolling in the wizard, never randi()) before the sim starts.
var seed := 0
var region_size := "medium"
var resource_abundance := "normal"
var hazard_frequency := "normal"
var biome_variety := "varied"
var exploration_fog := true

# Founding [setup §5]
var band_size := 4
var temperament_leanings: Array = DEFAULT_LEANINGS.duplicate()
var culture_flavor := ""
# "" here; a display name is generated by the New Game wizard, not the sim [setup §5].
var colony_name := ""

# Gameplay constant [algo §14 ⚙️ ~300]
var quicken_budget := DEFAULT_QUICKEN_BUDGET


func basin_count() -> int:
	return REGION_SIZES[region_size]


## Coerce every field back into its legal range; invalid level strings
## fall back to their spec defaults. Idempotent.
func normalize() -> void:
	generation_pace = _pick(generation_pace, GENERATION_PACES, "balanced")
	mortality = _pick(mortality, MORTALITIES, "normal")
	discovery_pace = _pick(discovery_pace, DISCOVERY_PACES, "normal")
	divinity = _pick(divinity, DIVINITIES, "normal")
	chaos = _pick(chaos, CHAOS_LEVELS, "normal")
	civilization_scale = _pick(civilization_scale, CIVILIZATION_SCALES, "kingdom")
	faith_enlightenment = _pick(faith_enlightenment, FAITH_MODES, "mild_drift")
	region_size = _pick(region_size, REGION_SIZES.keys(), "medium")
	resource_abundance = _pick(resource_abundance, RESOURCE_ABUNDANCES, "normal")
	hazard_frequency = _pick(hazard_frequency, HAZARD_FREQUENCIES, "normal")
	biome_variety = _pick(biome_variety, BIOME_VARIETIES, "varied")
	band_size = clampi(band_size, BAND_SIZE_MIN, BAND_SIZE_MAX)
	quicken_budget = maxi(quicken_budget, 1)
	var leanings := []
	for entry in temperament_leanings:
		if entry in TEMPERAMENTS and not entry in leanings and leanings.size() < MAX_LEANINGS:
			leanings.append(entry)
	if leanings.is_empty():
		leanings = DEFAULT_LEANINGS.duplicate()
	temperament_leanings = leanings


func _pick(value: String, allowed: Array, fallback: String) -> String:
	return value if value in allowed else fallback
